/**
 * Plan Generation Service with Safety Guardrails
 * 
 * This service generates personalized fitness and nutrition plans using LLM
 * and applies comprehensive safety filters and guardrails.
 */

const openai = require('../lib/openaiClient');
const supabaseClient = require('../lib/supabaseClient');
const { v4: uuidv4 } = require('uuid');

class PlanGenerationService {
  constructor() {
    this.GENERATOR_VERSION = 'v2.0-guardrails';
    this.MAX_CALORIC_DEFICIT_PER_WEEK = 0.01; // 1% of body weight per week
    this.HIGH_RISK_EXERCISES = [
      'deadlifts', 'heavy squats', 'overhead press', 'bench press', 'power cleans',
      'olympic lifts', 'plyometrics', 'jumping exercises', 'high impact cardio',
      'sprints', 'burpees', 'mountain climbers'
    ];
    this.MEDIUM_RISK_EXERCISES = [
      'planks', 'pull-ups', 'push-ups', 'lunges', 'step-ups',
      'kettlebell swings', 'battle ropes', 'box jumps'
    ];
  }

  /**
   * Main plan generation method with safety guardrails
   * @param {Object} params - Generation parameters
   * @param {string} params.user_id - User ID
   * @param {string} params.session_id - Onboarding session ID  
   * @param {Object} params.required_fields_snapshot - Canonical fields + confidence
   * @param {Object} params.profile_extras - Medications, medical conditions, etc.
   * @param {Object} params.user_summaries - User memories/summaries if available
   * @param {boolean} params.force - Force generation bypassing some checks
   * @returns {Object} Generated plan with guardrails applied
   */
  async generatePlan({
    user_id,
    session_id,
    required_fields_snapshot,
    profile_extras = {},
    user_summaries = {},
    force = false
  }) {
    console.log(`🎯 Starting plan generation for user ${user_id}, session ${session_id}`);

    try {
      // Step 1: Input validation and safety analysis
      const safetyAnalysis = this.analyzeSafetyRequirements(required_fields_snapshot, profile_extras);
      console.log(`🛡️ Safety analysis completed: ${safetyAnalysis.level} risk`);

      // Step 2: Generate base plan using LLM
      const basePlan = await this.generateBasePlan(required_fields_snapshot, profile_extras, user_summaries);
      console.log(`🤖 Base plan generated by LLM`);

      // Step 3: Apply safety guardrails
      const guardedPlan = this.applyPostProcessingGuardrails(basePlan, safetyAnalysis, required_fields_snapshot);
      console.log(`⚡ Safety guardrails applied`);

      // Step 4: Validate schedule constraints
      const validatedPlan = this.validateScheduleConstraints(guardedPlan, required_fields_snapshot);
      console.log(`📅 Schedule validation completed`);

      // Step 5: Determine final plan status
      const planStatus = this.determinePlanStatus(safetyAnalysis, validatedPlan);
      const needsSafetyReview = safetyAnalysis.level === 'high' || safetyAnalysis.requiresReview;

      // Step 6: Prepare final plan record
      const planRecord = {
        id: uuidv4(),
        user_id,
        plan_json: validatedPlan,
        summary_text: this.generatePlanSummary(validatedPlan, safetyAnalysis),
        generator_version: this.GENERATOR_VERSION,
        required_fields_snapshot,
        trigger_reason: force ? 'manual' : 'auto',
        status: planStatus,
        generated_at: new Date().toISOString(),
        // Additional safety tracking
        safety_analysis: safetyAnalysis,
        guardrails_applied: validatedPlan.guardrails_applied || [],
        created_at: new Date().toISOString()
      };

      // Step 7: Update profile safety review flag if needed
      if (needsSafetyReview) {
        await this.updateProfileSafetyFlags(user_id, safetyAnalysis);
      }

      return {
        success: true,
        plan: planRecord,
        safety_review_required: needsSafetyReview,
        guardrails_triggered: validatedPlan.guardrails_applied?.length > 0,
        analysis: safetyAnalysis
      };

    } catch (error) {
      console.error('❌ Plan generation failed:', error);
      return {
        success: false,
        error: error.message,
        plan: null
      };
    }
  }

  /**
   * Analyze safety requirements from user data
   */
  analyzeSafetyRequirements(fieldsSnapshot, profileExtras) {
    const analysis = {
      level: 'low',
      concerns: [],
      requiresReview: false,
      modifications: []
    };

    // Check for injury flags
    const injuryFlag = fieldsSnapshot.injury_flag_v1?.parsed_value?.value;
    const injuryDetails = fieldsSnapshot.injury_details_v1?.parsed_value?.value;
    
    if (injuryFlag === 'yes' || injuryDetails) {
      analysis.level = 'high';
      analysis.requiresReview = true;
      analysis.concerns.push({
        type: 'injury',
        severity: this.assessInjurySeverity(injuryDetails),
        description: injuryDetails || 'User reported injuries',
        recommended_action: 'Remove high-risk exercises, conservative intensity'
      });
      analysis.modifications.push('reduce_exercise_intensity', 'remove_high_risk_exercises');
    }

    // Check medical conditions
    const medicalConditions = profileExtras.medical_conditions || fieldsSnapshot.medical_conditions_v1?.parsed_value?.value;
    if (medicalConditions && medicalConditions !== 'none') {
      analysis.level = analysis.level === 'high' ? 'high' : 'medium';
      analysis.concerns.push({
        type: 'medical_condition',
        description: medicalConditions,
        recommended_action: 'Conservative approach, possible medical clearance needed'
      });
      analysis.modifications.push('conservative_intensity');
      
      // High-risk conditions require review
      const highRiskConditions = ['heart', 'cardiac', 'diabetes', 'hypertension', 'pregnancy'];
      if (highRiskConditions.some(condition => 
        medicalConditions.toLowerCase().includes(condition))) {
        analysis.requiresReview = true;
      }
    }

    // Check medications
    if (profileExtras.medications) {
      analysis.concerns.push({
        type: 'medications',
        description: profileExtras.medications,
        recommended_action: 'Consider drug-exercise interactions'
      });
      analysis.modifications.push('monitor_interactions');
    }

    // Check age extremes (if available)
    const age = this.calculateAge(fieldsSnapshot.date_of_birth_v1?.parsed_value?.value);
    if (age && (age < 16 || age > 65)) {
      analysis.level = analysis.level === 'high' ? 'high' : 'medium';
      analysis.concerns.push({
        type: 'age_consideration',
        description: `Age: ${age} years`,
        recommended_action: age < 16 ? 'Youth-appropriate programming' : 'Senior-friendly modifications'
      });
      analysis.modifications.push('age_appropriate_programming');
    }

    return analysis;
  }

  /**
   * Generate base plan using LLM pipeline
   */
  async generateBasePlan(fieldsSnapshot, profileExtras, userSummaries) {
    // Extract key fields
    const goal = fieldsSnapshot.primary_goal_v1?.parsed_value?.value || 'general_fitness';
    const currentWeight = fieldsSnapshot.current_weight_v1?.parsed_value?.value;
    const targetWeight = fieldsSnapshot.target_weight_v1?.parsed_value?.value;
    const height = fieldsSnapshot.height_v1?.parsed_value?.value;
    const activityLevel = fieldsSnapshot.activity_level_v1?.parsed_value?.value || 'moderately_active';
    const availability = fieldsSnapshot.time_availability_v1?.parsed_value?.value || '30_minutes';
    const workoutSetup = fieldsSnapshot.workout_setup_v1?.parsed_value?.value || 'home_basic_equipment';
    const dietPreference = fieldsSnapshot.diet_preference_v1?.parsed_value?.value || 'balanced';
    const trainingExperience = fieldsSnapshot.training_experience_v1?.parsed_value?.value || 'beginner';

    // Build comprehensive prompt
    const prompt = `Create a comprehensive, personalized health and fitness plan.

USER PROFILE:
- Primary Goal: ${goal.replace(/_/g, ' ')}
- Current Weight: ${currentWeight || 'not specified'}kg
- Target Weight: ${targetWeight || 'not specified'}kg  
- Height: ${height || 'not specified'}cm
- Activity Level: ${activityLevel.replace(/_/g, ' ')}
- Training Experience: ${trainingExperience.replace(/_/g, ' ')}
- Available Time: ${availability.replace(/_/g, ' ')} per session
- Workout Setup: ${workoutSetup.replace(/_/g, ' ')}
- Diet Preference: ${dietPreference.replace(/_/g, ' ')}

${profileExtras.medical_conditions ? `Medical Considerations: ${profileExtras.medical_conditions}` : ''}
${profileExtras.medications ? `Medications: ${profileExtras.medications}` : ''}
${userSummaries.summary ? `User History: ${userSummaries.summary}` : ''}

Create a detailed plan in JSON format:
{
  "title": "Plan name",
  "duration_weeks": 12,
  "fitness_plan": {
    "weekly_structure": {
      "workout_days": ["Monday", "Wednesday", "Friday"],
      "rest_days": ["Tuesday", "Thursday", "Saturday", "Sunday"],
      "session_duration": "30-45 minutes"
    },
    "workout_program": {
      "week_1_4": {
        "focus": "Foundation Building",
        "exercises": [
          {
            "name": "Bodyweight Squats",
            "sets": 3,
            "reps": "10-15",
            "rest": "60 seconds",
            "progressions": ["Add jump at top", "Single leg squats"]
          }
        ]
      },
      "progression_strategy": "Increase intensity by 5-10% weekly"
    }
  },
  "nutrition_plan": {
    "daily_targets": {
      "calories": 2000,
      "protein_g": 120,
      "carbs_g": 200,
      "fats_g": 65
    },
    "meal_structure": {
      "breakfast": "High protein, moderate carbs",
      "lunch": "Balanced macros with vegetables",
      "dinner": "Lean protein, complex carbs",
      "snacks": "Optional protein-rich options"
    },
    "sample_meals": [
      {
        "meal": "breakfast",
        "option": "Greek yogurt with berries and nuts",
        "calories": 350,
        "protein": 20
      }
    ]
  },
  "lifestyle_recommendations": {
    "sleep": {
      "target_hours": "7-9",
      "quality_tips": ["Dark room", "Cool temperature", "No screens 1h before bed"]
    },
    "hydration": {
      "daily_target_ml": 2500,
      "timing": "500ml upon waking, consistent throughout day"
    },
    "stress_management": {
      "techniques": ["Deep breathing", "Walking", "Meditation"],
      "frequency": "5-10 minutes daily"
    }
  },
  "monitoring_metrics": {
    "weekly_measurements": ["Weight", "Waist circumference"],
    "performance_tracking": ["Workout completion", "Energy levels", "Sleep quality"],
    "adjustment_triggers": ["Plateau for 2+ weeks", "Persistent fatigue", "Loss of motivation"]
  },
  "safety_notes": []
}

Make the plan specific, actionable, and progressive. Use metric units. Be conservative with intensity for beginners.`;

    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        { 
          role: 'system', 
          content: 'You are an expert fitness and nutrition coach with 15+ years of experience. Create safe, effective, personalized plans that prioritize user safety and long-term success.' 
        },
        { role: 'user', content: prompt }
      ],
      max_tokens: 2000,
      temperature: 0.7
    });

    const planText = completion.choices?.[0]?.message?.content;
    if (!planText) {
      throw new Error('No response from LLM');
    }

    // Parse and validate JSON
    try {
      const cleaned = planText.replace(/^\s*```(?:json\s*)?/, '').replace(/```\s*$/, '').trim();
      const planJson = JSON.parse(cleaned);
      
      // Validate required structure
      if (!planJson.fitness_plan || !planJson.nutrition_plan) {
        throw new Error('Invalid plan structure from LLM');
      }
      
      return planJson;
    } catch (parseError) {
      console.error('LLM JSON parsing failed:', parseError);
      throw new Error('Failed to parse LLM response as valid JSON');
    }
  }

  /**
   * Apply post-processing safety guardrails
   */
  applyPostProcessingGuardrails(basePlan, safetyAnalysis, fieldsSnapshot) {
    const guardedPlan = JSON.parse(JSON.stringify(basePlan)); // Deep copy
    const appliedGuardrails = [];

    // Guardian 1: Remove high-risk exercises if injury/medical conditions present
    if (safetyAnalysis.modifications.includes('remove_high_risk_exercises')) {
      this.removeHighRiskExercises(guardedPlan);
      appliedGuardrails.push('removed_high_risk_exercises');
    }

    // Guardian 2: Set conservative intensity
    if (safetyAnalysis.modifications.includes('reduce_exercise_intensity') || 
        safetyAnalysis.modifications.includes('conservative_intensity')) {
      this.setConservativeIntensity(guardedPlan);
      appliedGuardrails.push('conservative_intensity_applied');
    }

    // Guardian 3: Add safety notes
    if (safetyAnalysis.concerns.length > 0) {
      this.addSafetyNotes(guardedPlan, safetyAnalysis);
      appliedGuardrails.push('safety_notes_added');
    }

    // Guardian 4: Enforce caloric limits
    const caloricLimits = this.enforceCaloricLimits(guardedPlan, fieldsSnapshot);
    if (caloricLimits.modified) {
      appliedGuardrails.push('caloric_limits_enforced');
    }

    // Guardian 5: Age-appropriate modifications
    if (safetyAnalysis.modifications.includes('age_appropriate_programming')) {
      this.applyAgeAppropriateModifications(guardedPlan, fieldsSnapshot);
      appliedGuardrails.push('age_appropriate_modifications');
    }

    guardedPlan.guardrails_applied = appliedGuardrails;
    guardedPlan.safety_level = safetyAnalysis.level;
    
    return guardedPlan;
  }

  /**
   * Remove high-risk exercises from workout plan
   */
  removeHighRiskExercises(plan) {
    if (!plan.fitness_plan?.workout_program) return;

    // Recursively search and replace high-risk exercises
    const searchAndReplace = (obj) => {
      if (Array.isArray(obj)) {
        return obj.filter(item => {
          if (typeof item === 'object' && item.name) {
            const exerciseName = item.name.toLowerCase();
            const isHighRisk = this.HIGH_RISK_EXERCISES.some(riskEx => 
              exerciseName.includes(riskEx.toLowerCase())
            );
            if (isHighRisk) {
              console.log(`🚫 Removed high-risk exercise: ${item.name}`);
            }
            return !isHighRisk;
          }
          return true;
        }).map(item => searchAndReplace(item));
      } else if (typeof obj === 'object' && obj !== null) {
        const result = {};
        for (const [key, value] of Object.entries(obj)) {
          result[key] = searchAndReplace(value);
        }
        return result;
      }
      return obj;
    };

    plan.fitness_plan.workout_program = searchAndReplace(plan.fitness_plan.workout_program);
  }

  /**
   * Set conservative intensity levels
   */
  setConservativeIntensity(plan) {
    if (plan.fitness_plan?.workout_program) {
      // Reduce sets and reps by 20-30%
      const reduceIntensity = (obj) => {
        if (Array.isArray(obj)) {
          return obj.map(item => reduceIntensity(item));
        } else if (typeof obj === 'object' && obj !== null) {
          const result = { ...obj };
          
          // Reduce sets
          if (result.sets && typeof result.sets === 'number') {
            result.sets = Math.max(1, Math.floor(result.sets * 0.7));
          }
          
          // Reduce reps (if it's a range, take lower end)
          if (result.reps && typeof result.reps === 'string') {
            const repsMatch = result.reps.match(/(\d+)-?(\d+)?/);
            if (repsMatch) {
              const lowerReps = Math.max(5, Math.floor(parseInt(repsMatch[1]) * 0.8));
              result.reps = repsMatch[2] ? `${lowerReps}-${Math.floor(parseInt(repsMatch[2]) * 0.8)}` : `${lowerReps}`;
            }
          }

          // Process nested objects
          for (const [key, value] of Object.entries(result)) {
            if (typeof value === 'object') {
              result[key] = reduceIntensity(value);
            }
          }
          
          return result;
        }
        return obj;
      };

      plan.fitness_plan.workout_program = reduceIntensity(plan.fitness_plan.workout_program);
    }

    // Reduce caloric deficit if weight loss goal
    if (plan.nutrition_plan?.daily_targets?.calories) {
      plan.nutrition_plan.daily_targets.calories = Math.floor(plan.nutrition_plan.daily_targets.calories * 1.1);
    }
  }

  /**
   * Add safety notes to plan
   */
  addSafetyNotes(plan, safetyAnalysis) {
    if (!plan.safety_notes) {
      plan.safety_notes = [];
    }

    // Add general safety note
    plan.safety_notes.push({
      type: 'general',
      message: '⚠️ This plan has been modified based on your health profile. Please consult with a healthcare provider before starting any new exercise program.',
      priority: 'high'
    });

    // Add specific notes based on concerns
    safetyAnalysis.concerns.forEach(concern => {
      let message;
      switch (concern.type) {
        case 'injury':
          message = `🩹 Modified for injury considerations: ${concern.description}. Avoid movements that cause pain or discomfort.`;
          break;
        case 'medical_condition':
          message = `🏥 Consider medical clearance due to: ${concern.description}. Monitor symptoms during exercise.`;
          break;
        case 'medications':
          message = `💊 Be aware of potential medication interactions with exercise. Stay hydrated and monitor how you feel.`;
          break;
        case 'age_consideration':
          message = `🎂 Plan adapted for age-appropriate exercise. Progress gradually and listen to your body.`;
          break;
        default:
          message = `ℹ️ ${concern.recommended_action}`;
      }
      
      plan.safety_notes.push({
        type: concern.type,
        message,
        priority: concern.type === 'injury' || concern.type === 'medical_condition' ? 'high' : 'medium'
      });
    });
  }

  /**
   * Enforce caloric deficit/surplus limits
   */
  enforceCaloricLimits(plan, fieldsSnapshot) {
    const currentWeight = fieldsSnapshot.current_weight_v1?.parsed_value?.value;
    const targetWeight = fieldsSnapshot.target_weight_v1?.parsed_value?.value;
    
    if (!currentWeight || !targetWeight || !plan.nutrition_plan?.daily_targets?.calories) {
      return { modified: false };
    }

    const weightDifference = currentWeight - targetWeight;
    const isWeightLoss = weightDifference > 0;
    const maxWeeklyChange = currentWeight * this.MAX_CALORIC_DEFICIT_PER_WEEK; // 1% of body weight
    
    // Calculate reasonable caloric target (rough estimate: 7700 cal = 1kg fat)
    const maxWeeklyCaloricChange = maxWeeklyChange * 7700; // calories per week
    const maxDailyCaloricChange = maxWeeklyCaloricChange / 7; // calories per day
    
    // Estimate BMR (Harris-Benedict approximation - simplified)
    const estimatedBMR = currentWeight * 22; // Very rough estimate for planning
    const maintenanceCalories = estimatedBMR * 1.4; // Account for activity
    
    let targetCalories;
    if (isWeightLoss) {
      targetCalories = Math.max(
        maintenanceCalories - maxDailyCaloricChange,
        estimatedBMR * 1.2 // Never go below 120% of BMR
      );
    } else {
      targetCalories = maintenanceCalories + maxDailyCaloricChange;
    }

    const currentPlanCalories = plan.nutrition_plan.daily_targets.calories;
    const difference = Math.abs(currentPlanCalories - targetCalories);
    
    if (difference > 200) { // Only adjust if significantly different
      plan.nutrition_plan.daily_targets.calories = Math.round(targetCalories);
      
      // Add note about caloric adjustment
      if (!plan.safety_notes) plan.safety_notes = [];
      plan.safety_notes.push({
        type: 'caloric_adjustment',
        message: `📊 Caloric target adjusted to ${Math.round(targetCalories)} for safe ${isWeightLoss ? 'weight loss' : 'weight gain'} (max 1% body weight per week).`,
        priority: 'medium'
      });
      
      return { modified: true, adjusted_calories: Math.round(targetCalories) };
    }

    return { modified: false };
  }

  /**
   * Apply age-appropriate modifications
   */
  applyAgeAppropriateModifications(plan, fieldsSnapshot) {
    const age = this.calculateAge(fieldsSnapshot.date_of_birth_v1?.parsed_value?.value);
    if (!age) return;

    if (age < 16) {
      // Youth modifications
      if (!plan.safety_notes) plan.safety_notes = [];
      plan.safety_notes.push({
        type: 'youth_programming',
        message: '👶 Youth-focused program emphasizing proper form, fun activities, and avoiding overtraining.',
        priority: 'high'
      });

      // Reduce session frequency and duration
      if (plan.fitness_plan?.weekly_structure) {
        plan.fitness_plan.weekly_structure.session_duration = '20-30 minutes';
      }
    } else if (age > 65) {
      // Senior modifications
      if (!plan.safety_notes) plan.safety_notes = [];
      plan.safety_notes.push({
        type: 'senior_programming',
        message: '👴 Senior-friendly program emphasizing balance, flexibility, and joint-friendly exercises.',
        priority: 'high'
      });

      // Add balance and flexibility focus
      if (plan.fitness_plan?.workout_program) {
        plan.fitness_plan.focus_areas = ['balance', 'flexibility', 'functional_strength'];
      }
    }
  }

  /**
   * Validate schedule fits user availability
   */
  validateScheduleConstraints(plan, fieldsSnapshot) {
    const availability = fieldsSnapshot.time_availability_v1?.parsed_value?.value;
    const preferredTime = fieldsSnapshot.preferred_time_v1?.parsed_value?.value;
    
    if (!availability || !plan.fitness_plan?.weekly_structure) {
      return plan;
    }

    // Parse availability (e.g., "30_minutes", "1_hour")
    const availableMinutes = this.parseAvailabilityToMinutes(availability);
    
    // Check if planned sessions fit availability
    const plannedDuration = plan.fitness_plan.weekly_structure.session_duration;
    const plannedMinutes = this.parseSessionDurationToMinutes(plannedDuration);

    if (plannedMinutes > availableMinutes + 10) { // 10 min buffer
      // Adjust session duration
      plan.fitness_plan.weekly_structure.session_duration = availability.replace('_', ' ');
      
      if (!plan.safety_notes) plan.safety_notes = [];
      plan.safety_notes.push({
        type: 'schedule_adjustment',
        message: `⏰ Workout duration adjusted to fit your ${availability.replace('_', ' ')} availability.`,
        priority: 'low'
      });
    }

    // Add preferred time note if available
    if (preferredTime) {
      if (!plan.lifestyle_recommendations) plan.lifestyle_recommendations = {};
      plan.lifestyle_recommendations.optimal_workout_time = preferredTime.replace('_', ' ');
    }

    return plan;
  }

  /**
   * Determine final plan status based on safety analysis
   */
  determinePlanStatus(safetyAnalysis, plan) {
    // High-risk cases require draft status for human review
    if (safetyAnalysis.level === 'high' || safetyAnalysis.requiresReview) {
      return 'draft';
    }

    // Plans with multiple guardrails applied might need review
    if (plan.guardrails_applied?.length >= 3) {
      return 'draft';
    }

    // Otherwise, plan is ready to be active
    return 'active';
  }

  /**
   * Generate plan summary text
   */
  generatePlanSummary(plan, safetyAnalysis) {
    const goalType = plan.title || 'Personalized Fitness Plan';
    const duration = plan.duration_weeks || 12;
    const safetyLevel = safetyAnalysis.level;
    const guardrailsCount = plan.guardrails_applied?.length || 0;

    let summary = `${goalType} - ${duration} week program`;
    
    if (guardrailsCount > 0) {
      summary += ` with ${guardrailsCount} safety modification(s)`;
    }

    if (safetyLevel === 'high') {
      summary += ' (Requires safety review)';
    } else if (safetyLevel === 'medium') {
      summary += ' (Moderate safety considerations)';
    }

    return summary;
  }

  /**
   * Update profile safety flags
   */
  async updateProfileSafetyFlags(userId, safetyAnalysis) {
    try {
      const updateData = {
        safety_review_required: safetyAnalysis.requiresReview,
        injury_severity: this.calculateInjurySeverity(safetyAnalysis),
        updated_at: new Date().toISOString()
      };

      await supabaseClient
        .from('profiles')
        .update(updateData)
        .eq('user_id', userId);

      console.log(`🛡️ Profile safety flags updated for user ${userId}`);
    } catch (error) {
      console.error('Failed to update profile safety flags:', error);
    }
  }

  /**
   * Helper methods
   */
  calculateAge(dateOfBirth) {
    if (!dateOfBirth) return null;
    const birthDate = new Date(dateOfBirth);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    return age;
  }

  assessInjurySeverity(injuryDetails) {
    if (!injuryDetails) return 1;
    
    const details = injuryDetails.toLowerCase();
    const severeKeywords = ['surgery', 'fracture', 'torn', 'ruptured', 'severe', 'chronic'];
    const moderateKeywords = ['sprain', 'strain', 'pain', 'ache', 'sore', 'stiff'];
    
    if (severeKeywords.some(keyword => details.includes(keyword))) {
      return 3; // Severe
    } else if (moderateKeywords.some(keyword => details.includes(keyword))) {
      return 2; // Moderate  
    }
    return 1; // Mild
  }

  calculateInjurySeverity(safetyAnalysis) {
    const injuryConcern = safetyAnalysis.concerns.find(c => c.type === 'injury');
    return injuryConcern ? injuryConcern.severity || 1 : 0;
  }

  parseAvailabilityToMinutes(availability) {
    const timeMap = {
      '15_minutes': 15,
      '30_minutes': 30,
      '45_minutes': 45,
      '1_hour': 60,
      '90_minutes': 90,
      '2_hours': 120
    };
    return timeMap[availability] || 30; // Default to 30 minutes
  }

  parseSessionDurationToMinutes(duration) {
    if (!duration) return 30;
    const matches = duration.match(/(\d+)/g);
    return matches ? parseInt(matches[0]) : 30;
  }
}

module.exports = PlanGenerationService;