const express = require('express');
const router = express.Router();
const supabase = require('../lib/supabaseClient');
const openai = require('../lib/openaiClient');
const Joi = require('joi');

// simple validation
const schema = Joi.object({
  goal: Joi.string().required(),
  preferences: Joi.object().optional()
});

/**
 * POST /plans/generate
 * body: { userId?, goal: string, preferences? }
 * - Generates a plan (workout + meal) using LLM
 * - Saves plan to "plans" table in Supabase
 *
 * NOTE: This code expects the following columns to exist in `plans`:
 *   - id (uuid) [optional]
 *   - user_id (uuid)
 *   - plan_json (jsonb)
 *   - generated_at (timestamptz)
 *   - generator_version (text)
 *   - metadata (jsonb) [optional]
 *   - created_at (timestamptz DEFAULT now()) [DB default]
 *   - updated_at (timestamptz DEFAULT now()) [DB trigger updates on update]
 */
router.post('/generate', async (req, res) => {
  const { error, value } = schema.validate(req.body);
  if (error) return res.status(400).json({ error: error.message });

  const { goal, preferences = {} } = value;

  try {
    // 1) Build a prompt for the model
    const prompt = `
Create a concise, actionable 7-day workout + meal plan for the user.

Goal: ${goal}
Preferences: ${JSON.stringify(preferences)}
Format: JSON with keys: { title, duration_weeks, daily: [{ day, workout: "...", meals: ["...","..."], notes: "..." }] }
Return only valid JSON.
Be concise and use metric units where appropriate.
    `;

    // 2) Call OpenAI (chat/completions) - adjust call to match your SDK if needed
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini', // replace with your allowed model
      messages: [
        { role: 'system', content: 'You are a helpful fitness coach.' },
        { role: 'user', content: prompt }
      ],
      max_tokens: 900
    });

    const planText = completion.choices?.[0]?.message?.content ?? null;
    if (!planText) throw new Error('No response from LLM');

    // try to parse JSON
    let planJson = null;
    try {
      // strip markdown fences if present
      const cleaned = planText.replace(/^\s*```(?:json\s*)?/, '').replace(/```\s*$/, '').trim();
      planJson = JSON.parse(cleaned);
    } catch (e) {
      // fallback: store raw text inside the JSON to avoid crashes
      planJson = { raw: planText };
    }

    // 3) Save to Supabase 'plans' table
    const insertPayload = {
      // Note: DB schema expects UUID referencing users.id; we're using Firebase Auth.
      // Until a mapping exists, keep null and persist UID in metadata for joins.
      user_id: null,
      plan_json: planJson,                      // matches DB column
      generated_at: new Date().toISOString(),   // timestamp when plan was generated by LLM
      generator_version: 'gpt-4o-mini',         // update as needed
      metadata: {
        raw_text: planText,
        auth_uid: req.user?.id || null,
        prompt_summary: {
          goal,
          preferences
        }
      }
    };

    const { data, error: supError } = await supabase
      .from('plans')
      .insert([insertPayload])
      .select()
      .single();

    if (supError) {
      console.error('Supabase insert error', supError);
      // still return plan to client but indicate not saved
      return res.status(201).json({ plan: planJson, saved: false, supabaseError: supError });
    }

  return res.status(201).json({ plan: planJson, saved: true, record: data });

  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
